import { test, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/private-notes.js';
const ADMIN='18d029c2-ea87-48f4-a028-bc8d3e793003';
const ID='e6ab057d-73d0-4839-9d0e-5c0172052f00';
const originalFetch=globalThis.fetch;
const env={...process.env};
afterEach(()=>{globalThis.fetch=originalFetch;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);});
function setup(){process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='sb_publishable_test';process.env.NOTES_ADMIN_USER_ID=ADMIN;process.env.NOTES_ADMIN_EMAIL='owner@example.test';process.env.NODE_ENV='production';}
async function call(action='session',method='GET',body,options={}){setup();const req={method,query:{action,...options.query},body,headers:{host:'portfolio.test',origin:'https://portfolio.test','content-type':'application/json',cookie:'nourah_notes_session=test-token',...options.headers}};const res={code:200,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(data){this.data=data;return this}};await handler(req,res);return res;}
function mock(fn){const calls=[];globalThis.fetch=async(url,opt)=>{calls.push({url,opt});return fn(url,opt,calls.length)};return calls;}
const ok=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers});
test('logged out cannot access session, list, update or delete',async()=>{const calls=mock(()=>{throw Error('must not query')});for(const [action,method] of [['session','GET'],['notes','GET'],['update','PATCH'],['delete','DELETE']]){const r=await call(action,method,{id:ID,confirm:true,is_read:true},{headers:{cookie:''}});assert.equal(r.code,404);assert.equal(r.data.error,'Not found');}assert.equal(calls.length,0)});
test('non-owner valid session cannot read, update or delete',async()=>{const calls=mock(()=>ok({id:'other-user'}));for(const [a,m] of [['notes','GET'],['update','PATCH'],['delete','DELETE']])assert.equal((await call(a,m,{id:ID,confirm:true,is_read:true})).code,404);assert.ok(calls.every(c=>c.url.endsWith('/auth/v1/user')))});
test('expired session clears cookie and returns neutral response',async()=>{mock(()=>ok({},401));const r=await call();assert.equal(r.code,404);assert.match(r.headers['Set-Cookie'].join(';'),/Max-Age=0/)});
test('owner login sets only an HttpOnly Secure Strict cookie',async()=>{mock(()=>ok({user:{id:ADMIN},access_token:'verified-jwt',refresh_token:'not-stored',expires_in:3600}));const r=await call('login','POST',{email:'owner@example.test',password:'test-only-password'});assert.equal(r.code,200);assert.deepEqual(r.data,{authorized:true});assert.match(r.headers['Set-Cookie'].join(';'),/HttpOnly; SameSite=Strict/);assert.match(r.headers['Set-Cookie'].join(';'),/Secure/);assert.ok(!JSON.stringify(r.data).includes('not-stored'));assert.match(r.headers['Set-Cookie'][1],/HttpOnly/);assert.match(r.headers['Set-Cookie'][1],/Max-Age=2592000/)});
test('other account login is rejected and revoked',async()=>{const calls=mock((u)=>u.includes('/token?')?ok({user:{id:'other'},access_token:'other-token'}):ok({}));assert.equal((await call('login','POST',{email:'other@example.test',password:'test'})).code,401);assert.ok(calls.some(c=>c.url.includes('/logout?')))});
test('incorrect password has generic response',async()=>{mock(()=>ok({message:'private raw detail'},400));const r=await call('login','POST',{email:'owner@example.test',password:'test'});assert.equal(r.code,401);assert.ok(!JSON.stringify(r).includes('private raw detail'))});
test('cross-origin mutations and login are rejected before authentication',async()=>{const calls=mock(()=>{throw Error('no fetch')});for(const [a,m] of [['login','POST'],['update','PATCH'],['delete','DELETE'],['logout','POST']])assert.equal((await call(a,m,{}, {headers:{origin:'https://evil.test'}})).code,403);assert.equal(calls.length,0)});
test('owner reads use user JWT and publishable key, with pagination and counts',async()=>{const rows=Array.from({length:51},(_,i)=>({id:String(i)}));const calls=mock((u,o)=>u.endsWith('/user')?ok({id:ADMIN}):o.method==='HEAD'?new Response(null,{headers:{'content-range':'0-0/51'}}):ok(rows));const r=await call('notes','GET',undefined,{query:{filter:'new',offset:'50'}});assert.equal(r.code,200);assert.equal(r.data.notes.length,50);assert.equal(r.data.hasMore,true);assert.equal(r.data.total,51);const db=calls.filter(c=>c.url.includes('/rest/'));assert.ok(db.every(c=>c.opt.headers.Authorization==='Bearer test-token'&&c.opt.headers.apikey==='sb_publishable_test'));assert.ok(db[0].url.includes('offset=50&is_read=eq.false'))});
test('owner can update read/favorite metadata',async()=>{const calls=mock(u=>u.endsWith('/user')?ok({id:ADMIN}):ok([{id:ID,is_read:true,is_favorite:true}]));const r=await call('update','PATCH',{id:ID,is_read:true,is_favorite:true});assert.equal(r.code,200);assert.deepEqual(JSON.parse(calls[1].opt.body),{is_read:true,is_favorite:true})});
test('message changes and invalid metadata rejected',async()=>{mock(()=>ok({id:ADMIN}));for(const data of [{id:ID,note:'overwrite'},{id:ID,is_read:'yes'},{id:'bad',is_read:true},{id:ID}])assert.equal((await call('update','PATCH',data)).code,400)});
test('delete requires explicit confirmation',async()=>{const calls=mock(()=>ok({id:ADMIN}));assert.equal((await call('delete','DELETE',{id:ID})).code,400);assert.equal(calls.length,1)});
test('confirmed owner delete is scoped to validated ID',async()=>{const calls=mock(u=>u.endsWith('/user')?ok({id:ADMIN}):ok([{id:ID}]));const r=await call('delete','DELETE',{id:ID,confirm:true});assert.equal(r.code,200);assert.equal(calls[1].opt.method,'DELETE');assert.ok(calls[1].url.endsWith('id=eq.'+ID))});
test('database errors are sanitized and never report success',async()=>{mock(u=>u.endsWith('/user')?ok({id:ADMIN}):ok({message:'secret database details'},500));const r=await call('update','PATCH',{id:ID,is_read:true});assert.equal(r.code,502);assert.ok(!JSON.stringify(r.data).includes('secret'))});
test('sign out clears cookie and revokes session',async()=>{const calls=mock(()=>ok({}));const r=await call('logout','POST');assert.equal(r.code,200);assert.match(r.headers['Set-Cookie'].join(';'),/Max-Age=0/);assert.ok(calls[0].url.includes('/logout?scope=local'))});
test('cache and robots headers protect every response',async()=>{mock(()=>ok({id:ADMIN}));const r=await call();assert.equal(r.headers['Cache-Control'],'private, no-store');assert.equal(r.headers['X-Robots-Tag'],'noindex, nofollow, noarchive')});

test('passcode uses server owner email, ignoring a supplied email',async()=>{const calls=mock(()=>ok({user:{id:ADMIN},access_token:'jwt',refresh_token:'refresh',expires_in:3600}));const r=await call('login','POST',{email:'attacker@example.test',password:'test-passcode'});assert.equal(r.code,200);assert.equal(JSON.parse(calls[0].opt.body).email,'owner@example.test')});
test('remembered browser renews expired access and rotates HttpOnly cookies',async()=>{const calls=mock(u=>u.includes('grant_type=refresh_token')?ok({user:{id:ADMIN},access_token:'renewed',refresh_token:'rotated',expires_in:3600}):ok({id:ADMIN}));const r=await call('session','GET',undefined,{headers:{cookie:'nourah_notes_refresh=remembered'}});assert.equal(r.code,200);assert.equal(calls.length,2);assert.ok(calls[0].url.includes('refresh_token'));assert.match(r.headers['Set-Cookie'][1],/rotated/);assert.deepEqual(r.data,{authorized:true})});
test('revoked refresh returns locked state and clears both cookies',async()=>{mock(()=>ok({},400));const r=await call('session','GET',undefined,{headers:{cookie:'nourah_notes_refresh=revoked'}});assert.equal(r.code,404);assert.ok(r.headers['Set-Cookie'].every(c=>c.includes('Max-Age=0')))});
test('non-owner refresh can never open notes',async()=>{mock(()=>ok({user:{id:'other'},access_token:'other',refresh_token:'other-refresh'}));const r=await call('notes','GET',undefined,{headers:{cookie:'nourah_notes_refresh=wrong-account'}});assert.equal(r.code,404)});
